<!doctype html>
<!--[if lt IE 7]>		
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="zxx">
   <![endif]-->
   <!--[if IE 7]>			
   <html class="no-js lt-ie9 lt-ie8" lang="zxx">
      <![endif]-->
      <!--[if IE 8]>			
      <html class="no-js lt-ie9" lang="zxx">
         <![endif]-->
         <!--[if gt IE 8]><!-->	
         <html class="no-js" lang="zxx">
            <!--<![endif]-->
            <head>
               <meta charset="utf-8">
               <meta http-equiv="X-UA-Compatible" content="IE=edge">
               <title>e-aukcije - </title>
               <meta name="viewport" content="width=device-width, initial-scale=1">
               <link rel="apple-touch-icon" href="apple-touch-icon.png">
               <link rel="stylesheet" href="css/bootstrap.min.css">
               <link rel="stylesheet" href="css/normalize.css">
               <link rel="stylesheet" href="css/font-awesome.min.css">
               <link rel="stylesheet" href="css/jquery.countdown.css">
               <link rel="stylesheet" href="css/customScrollbar.css">
               <link rel="stylesheet" href="css/jquery-ui.css">
               <link rel="stylesheet" href="css/owl.theme.css">
               <link rel="stylesheet" href="css/prettyPhoto.css">
               <link rel="stylesheet" href="css/owl.carousel.css">
               <link rel="stylesheet" href="css/prettyPhoto.css">
               <link rel="stylesheet" href="css/jquery.fullPage.css">
               <link rel="stylesheet" href="css/transitions.css">
               <link rel="stylesheet" href="css/main.css">
               <link rel="stylesheet" href="css/color.css">
               <link rel="stylesheet" href="css/responsive.css">
               <script src="js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
            </head>
            <body class="tg-login">
               <!--[if lt IE 8]>
               <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
               <![endif]-->
               <div id="tg-wrapper" class="tg-wrapper tg-haslayout">
                  <?php include 'php/inc/header.inc'?>
                  <main id="tg-main" class="tg-main tg-haslayout">